---
title: "Gráficas avanzadas"
author: "Equipo 5"
date: '2025-04-22'
output:
  pdf_document: default
  html_document: default
---

***Link del repositorio de GitHub: https://github.com/MauricioVazquezM/Data_Visualization_Course_Project***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, fig.width=10)

# Libraries
library(MASS)  
library(ggplot2)
library(GGally)
library(mclust)
library(kableExtra)
library(FactoMineR)
library(knitr)
library(caret)
library(dplyr)
library(gridExtra)
library(corrplot)
library(ggcorrplot)
library(car)
library(lmtest)
library(tidyr)
library(scales)
```

```{r, echo=FALSE}
# Lectura de los datos
data <- read.csv("C:\\Users\\mauva\\OneDrive\\Documents\\ITAM\\10mo Semestre\\VISUALIZACION DE LA INFORMACION\\CODIGO\\PROJECT REPOSITORY\\Data_Visualization_Course_Project\\DATA\\ESGData_transformed.csv")
#head(data)
```

### Recordando los indicadores con menor cantidad de nulos

```{r, echo=FALSE}
# Calcular cantidad de NA por indicador
na_por_indicador <- data %>%
  group_by(indicator_name) %>%
  summarise(valores_faltantes = sum(is.na(value)),
            total = n(),
            completes = 1 - valores_faltantes / total) %>%
  arrange(valores_faltantes)

# Seleccionar los 5 con menos nulos
top5_completos <- na_por_indicador %>%
  slice_head(n = 10)

# Mostrar en tabla estetica
knitr::kable(top5_completos, digits = 2, caption = "Indicadores con menor cantidad de valores nulos") %>%
  kableExtra::kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover"))
```
- Para este ejercicio, crearemos dos visualizaciones georeferenciadas para los indicadores de "Fertility rate, total (births per woman)" y "Population ages 65 and above (% of total population)".

### "Fertility rate, total (births per woman)"

```{r, echo=FALSE}

```

###  "Population ages 65 and above (% of total population)"

```{r, echo=FALSE}

```
